### ISSUE TITLE
diacritic order space modifier letters

### ISSUE THREAD

**Issue by bambooforest** [phoible/dev#126]
in coventions

http://phoible.github.io/conventions/

we give an explicit ordering in 1 though 8 and i thought the order within, say 8, should be kept (e.g. it makes sense to apply a rhotic hook typologically before a nasal release)

in the segments-features file though we have palatalized <ʲ> always before labialized <ʷ>, e.g.

sʲʷ
lʲʷ

which seems to be consistent with the literature. so should we change the conventions?

**Comment by drammock** [comment]
The way it's written in the conventions is forward-looking, and I was intending that the existing ordering would get revised when we implement the code for automatic generation of feature vectors from glyphs.  The ordering `labialized ʷ, palatalized ʲ, velarized ˠ, pharyngealized ˤ, glottalized ˀ, aspirated ʰ, ejective ʼ` was chosen based on a "front to back" rationale. Personally I don't feel strongly that we need to follow conventions in the literature on this particular point.   But because it's not implemented in the code yet, I also don't really mind changing that convention if you feel strongly that we should follow the literature here.

**Comment by bambooforest** [comment]
I'm working on the segments-feature file, so I can update accordingly and push so you can review.

**Comment by drammock** [comment]
OK.  though to clarify:  I was expecting that the re-ordering would not need to be manually done (I've got R code that seems to do it correctly, but it's not merged in because it's not tested carefully enough yet).  So unless you want to do this now for other reasons, I don't advise spending the time to do it manually.

**Comment by bambooforest** [comment]
OK. I'm adding new segment types (seems to always be one or two per incoming inventory), but I won't bother cleaning up the other issues until we re-address them with the code. (Will still get your OK on the new feature vectors though :)

**Comment by drammock** [comment]
closed by #129 as no longer relevant (component ordering is now automated)
