### ISSUE TITLE
f is not f

### ISSUE THREAD

**Issue by bambooforest** [phoible/dev#149]
http://phoible.org/languages/nam

it is a bilabial fricative in: Hoddinott 1988

the symbol <f> in the bilabial fricatives column seems to be relatively common in descriptions (probably due to typographic ease)

**Comment by bambooforest** [comment]
Here's another example:

http://phoible.org/inventories/view/319

which lists /f ,v/ via UPSID, but in the original resource 

http://phoible.org/sources/krauss1975

on page 46 lists /f, v/ in the column with other labials, but see also page 47 paragraph 2 (note also the transliteration to Cyrillc on page 62).

This source (Jacobson 1975) also lists these segments under labial:

http://library.alaska.gov/hist/hist_docs/docs/anlm/05265040.pdf

**Comment by drammock** [comment]
I skimmed Jacobson 1975 and didn't find any relevant info about the phonology; just a note in the introduction that he wasn't going to discuss phonology because Krauss 1975 already covered it.  I would be hesitant to count it as an independent data point.  It seems odd that UPSID would have gotten that wrong, since Maddieson was so careful...  might be worth asking him about it.

**Comment by bambooforest** [comment]
In nam_hoddinott1988_phon.pdf the authors state "The bilabial stops /p/ and /b/ have the corresponding fricative /f/. Among older speakers it is usually a bilabial fricative produced without lip-rounding and is of low intensity. In younger speakers it is often a labio-dental. There are two allophones... [ɸ]... [β]...".

So it seems like the language is shifting to labiodental. Our research shows this happening in quite a few languages. I think it's best to keep these inventories as is and go with Maddieson's keen eye.
