### ISSUE TITLE
Inventrories assigned to Western Cham seem to belong to Eastern Cham

### ISSUE THREAD

**Issue by xrotwang** [phoible/dev#276]
Via @d97hah :

The inventories assigned to [Western Cham](https://phoible.org/languages/west2650) use a source ([Blood 1967](https://phoible.org/sources/blood1967)) which seems to be explicitly about Cham in Vietnam, i.e., Eastern Cham [cjm] not Cambodian or Western Cham [cja].

**Comment by bambooforest** [comment]
Thanks for this @xrotwang @d97hah .

Via Blood1967.pdf : 

"This description of Cham phonology is based on a study made while residing in the Cham village of Phuoc Dong near Phan Rang, central Vietnam, from May, 1960 to May, 1962."

The language code assignment was incorrect because:

http://web.phonetik.uni-frankfurt.de/L/L2411.html (UPSID 282)

states: "Cham is spoken mostly in Kampuchea but there are several speakers in Vietnam." suggesting Western Cham. 

Hence the assignment in WALS is also incorrect:

https://wals.info/refdb/record/Blood-1967
