### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by bambooforest** [phoible/dev#282]
@drammock -- what say you we take all these explanations about adding inventories from our email exchanges and create a contributing doc to point people to?

**Comment by drammock** [comment]
let's discuss this at our next meeting.  So far we've done a *lot* of oversight / QC and still miss some things.  That level of oversight is not free; I don't want to encourage contributions from the wider community only to have their PRs languish because we don't have time to rigorously review them.  Having a more robust test suite might change my mind...  might also be a reason to switch to new inventories coming in as JSON (because easier to validate automatically; saves us some QC work).

**Comment by bambooforest** [comment]
We agreed we'd skip opening contributions to the public.
