### ISSUE TITLE
add indicator columns for unusual language types

### ISSUE THREAD

**Issue by drammock** [phoible/dev#69]
Probably want separate columns for mixed, pidgin, creole, signed, ancient, extinct. Could also conceivably do a single column that had one of those strings or `NA` for each language. That would be more compact, but a bit harder to deal with if we had a language that was creole + signed, mixed + extinct, etc.

Closes #67

**Comment by drammock** [comment]
I have lists of MultiTree family codes for ancient/extinct/pidgin/creole/mixed/signed/unclassified languages, but not lists of individual ISO codes. Is it possible to get this for free as part of the genealogy info?

**Comment by bambooforest** [comment]
Can you give me an example? Don't most languages even if they are
extinct/pidgin/creole
have ISO 639-3 codes? (Ancient languages may be a different story; they
were documented by Anthony Aristar at Linguist List at some point in the
past <knee slap>.)

Remember also that the Ethnologue only display living languages, so just
because it may not display an extinct language by code doesn't mean the
code doesn't exist in ISO 639-3 -- you just have to look for it on the SIL
site that hosts the codes officially.

**Comment by drammock** [comment]
I guess what I meant was this: if we end up parsing genealogies (from
Ethnologue or wherever) then we should get info such as "is an isolate" for
free, but any other languages we have data for that aren't in Ethnologue
(e.g., ancient/extinct/pidgin/creole/mixed) will just have NULL values for
genealogy, and we won't have a good way to assign values to the "is this an
unusual language type" variable.  Alternatively, if we could use MultiTree
data, we would end up with the 4-character family codes, and my lists of
multitree family codes (from our Language paper analysis) is useful for
assigning the "unusual language type" variable.  So I guess this is a
question about how we integrate genealogy info, and where we get it from.

**Comment by bambooforest** [comment]
I think we should take all genealogy info from Glottolog -- so what we need
is Forkel's mechanism for getting Glottolog codes via ISO 639-3 mappings.
Then we can get a bunch of stuff "for free", not just genealogy.
