### ISSUE TITLE
voiceless breathy consonants

### ISSUE THREAD

**Issue by bambooforest** [phoible/dev#84]
gm  kck kʷʱ   kʷʱ
gm  kck pʱ pʱ
gm  kck tʱ tʱ
gm  kck tsʱ    tsʱ
gm  kck t̠ʃʱ t̠ʃʱ
gm  kck wʱ wʱ

in source: kck_mathangwane.PDF

**Comment by bambooforest** [comment]
Squib emailed.

**Comment by bambooforest** [comment]
@drammock - can we close this?

**Comment by drammock** [comment]
> The final set of sounds also found in Ikalanga are the breathy voice consonants / pʱ, tʱ, ɦ, t͜ʃʱ, t͜sʱ, kʷʱ, wʱ /....  I defer discussion of these breathy consonants until Chapter 6.

Unfortunately the scan I have doesn't include Chapter 6. But she does give minimal pairs for some of these, and there's nothing to suggest anything remarkable going on here, so since she clearly calls these "breathy voice" consonants several times, let's substitute in the voiced base glyphs, switch the diacritic and drop the tiebar: /b̤ d̤ ɦ d̠̤ʒ̤ d̤z̤ ɡ̤ʷ w̤/.

**Comment by bambooforest** [comment]
@drammock what do you mean here by ɦ ? it's listed in the inventory as is. i've updated the rest (but see email regarding multiple breathy diacritics...).

**Comment by drammock** [comment]
ɦ shouldn't change.  Sorry I just included it because it was in her original quote, to keep the same order.

**Comment by bambooforest** [comment]
Ok. I've updated this in the branch `fix-remaining-inventory-errors`
